version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6

  redis-node-1:
    image: redis:6.2
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-1-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:6.2
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-2-data:/data
    ports:
      - "6380:6380"
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:6.2
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-3-data:/data
    ports:
      - "6381:6381"
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:6.2
    command: redis-server --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-4-data:/data
    ports:
      - "6382:6382"
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:6.2
    command: redis-server --port 6383 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-5-data:/data
    ports:
      - "6383:6383"
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:6.2
    command: redis-server --port 6384 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-node-6-data:/data
    ports:
      - "6384:6384"
    networks:
      - redis-cluster

  redis-cluster-setup:
    image: redis:6.2
    command: "sh -c 'sleep 10 && echo yes | redis-cli --cluster create redis-node-1:6379 redis-node-2:6380 redis-node-3:6381 redis-node-4:6382 redis-node-5:6383 redis-node-6:6384 --cluster-replicas 1'"
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - redis-cluster

networks:
  redis-cluster:

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:
